### ISSUE TITLE
Errors while running npm install

### ISSUE THREAD

**Issue by pRizz** [loehnertz/Tanglestash#2]
Logs:

```../src/ffi.cc:111:100: error: no viable conversion from 'v8::PropertyAttribute' to 'Local<v8::Value>'
  target->ForceSet(Nan::New<String>("RTLD_NEXT").ToLocalChecked(), WrapPointer((char *)RTLD_NEXT), static_cast<PropertyAttribute>(ReadOnly | DontDelete));

.....

24 warnings and 10 errors generated.
make: *** [Release/obj.target/ffi_bindings/src/ffi.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:160:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:12)
gyp ERR! System Darwin 17.4.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/.../Tanglestash/node_modules/ffi
gyp ERR! node -v v9.4.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ffi@2.2.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ffi@2.2.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/.../.npm/_logs/2018-02-04T20_07_54_871Z-debug.log
```

**Comment by loehnertz** [comment]
Hey :blush:
So awesome that especially you found my project. I really like your projects and been following them for quite a time. I came across so many transactions by your spammer while developing `Tanglestash` :smile:

Regarding your issue:
The problem is that for some reason the dependency `ffi` which I am using to perform the PoW locally does not work with Node.js version 9 at the moment. There is a fix in the pipeline for that but so far you need to use version 8. For `Tanglestash` v3.1 I will try to look into that problem.
I will let you know, when I was able to fix that!

**Comment by pRizz** [comment]
Thanks for your kind words, I appreciate it!

Thanks, works with Node 8!

My basic workaround:
```
sudo npm i -g n
sudo n 8.0.0
```
